### ISSUE TITLE
error while downloading hmm data

### ISSUE THREAD

**Issue by hites77** [ukaraoz/microtrait-hmm#1]
I have successfully installed microtrait in R but when i followed the instructions :

download hmm assets from microtrait-hmm repository into the microtrait install directory
piggyback::pb_download("hmm.tar.gz", 
            				repo = "ukaraoz/test",
            				dest = file.path(.libPaths(),"microtrait", "extdata"))

it gives me error: 
Error in `$<-.data.frame`(`*tmp*`, "dest", value = c("/usr/local/lib/R/site-library/microtrait/extdata",  :
  replacement has 3 rows, data has 0
In addition: Warning messages:
1: In get_token() : Using default public GITHUB_TOKEN.
                     Please set your own token
2: In piggyback::pb_download("hmm.tar.gz", repo = "ukaraoz/test", dest = file.path(.libPaths(),  :
  file(s) hmm.tar.gz not found in repo ukaraoz/test

I found that there is no hmm.tar.gz file ukaraoz/test and nor in ukaraoz/microtrait-hmm

Please suggest possible solution

**Comment by ukaraoz** [comment]
After github changed the authentication method, the piggyback download function failed with .token=NULL option.
I took piggyback offline for now, and replaced it with a hard link to the hmm database.
