### ISSUE TITLE
Total number of HMM profiles. 

### ISSUE THREAD

**Issue by indigo-qiqit** [ukaraoz/microtrait-hmm#2]
Hi,

I am trying to use the HMM profiles generated in this study to profile the traits of a set of genomes of my own. I found that the numbers of HMM profiles you uploaded here do not match the list of HMM profiles (Supplementary Table 2) in your original publication. Also, I am wondering what's the difference between hmm profiles in data/out/hmm/ and data.kb_hmmer/hmm ? 

Many thanks in advance!
Qiqi

**Comment by ukaraoz** [comment]
Hi Qiqi,
Thanks for your interest.
They are the same HMMs, one should be a subset of the other. In the
publication, the table refers to the ones that are part of the rules that
go into the standard pipeline. The larger set has additional HMMs that go
into rules that are not necessarily part of the standard pipeline but might
be useful to the user.
Hope that helps.
-------------------------
Ulas Karaoz, Ph.D.
Research Scientist
Climate and Ecosystems Sciences
Lawrence Berkeley National Laboratory

1 Cyclotron Road, Mail Stop: 70A-3317
Berkeley, CA 94720
Phone: ( <510-486-7490>510) 486 4118 (office)
***@***.***

**Comment by indigo-qiqit** [comment]
Hi Ulas,

Thank you very much for your prompt response. I just want to clarify things here: do you mean that the hmm files in data_kb_hmmer are the subset of data/out/hmm, and only the hmm files from data.kb_hmmer are needed for the standard pipeline? I noticed that you have 1,720 files in data/out/hmm but only 142 hmmfiles in data.kb_hmmer. In the meanwhile, you have ~2,200 entries in Supplementary Table 2 (microtrait_hmms) and ~1,900 entries in Supplementary Table 3(microtrait_hmms_benchmark). I am a bit confused about which data should I proceed with if I want to run a local hmmsearch and incorporate your microTrait rules later in my customized pipeline. 

Many thanks again!
Qiqi

**Comment by ukaraoz** [comment]
Hi,
data.kb_hmmer is a DOE-kbase specific subset of the full set. You should
ignore that in the context of the manuscript.
1720 should be a subset of 2200, i.e. those that make up the default rule
set. 1900 among 2200 those are the ones we benchmarked with Kegg protein
families, the rest isn't represented in KEGG so aren't benchmarked.
Hope that clarifies.


-------------------------
Ulas Karaoz, Ph.D.
Research Scientist
Climate and Ecosystems Sciences
Lawrence Berkeley National Laboratory

1 Cyclotron Road, Mail Stop: 70A-3317
Berkeley, CA 94720
Phone: ( <510-486-7490>510) 486 4118 (office)
***@***.***

**Comment by indigo-qiqit** [comment]
Thanks, Ulas. That's much clearer to me. I will proceed with the 1720 dataset then.
